# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\source\python\student\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from PyQt5.QtWidgets import QApplication
from qfluentwidgets import (
    NavigationAvatarWidget,
    NavigationItemPosition,
    MessageBox,
    FluentWindow,
    SplashScreen,
)
from qfluentwidgets import FluentIcon as FIF
from common.signal_bus import signalBus


class MainWindow(FluentWindow):
    def __init__(self):
        super().__init__()
        self.initWindow()
        self.homeInterface = ()
        self.studentManage = ()
        self.courseManage = ()
        self.scoreManage = ()
        self.teacherManage = ()
        self.adminManage = ()
        self.settingInterface = ()

        # effect enable
        self.navigationInterface.setAcrylicEnabled(isEnabled=True)
        #
        self.connectSignalToSlot()
        # init Navigation
        self.initNavigation()

    # 设置信号槽
    def connectSignalToSlot(self):
        print()

    def initNavigation(self):
        pos = NavigationItemPosition.SCROLL
        self.addSubInterface(self.homeInterface)
        self.addSubInterface(self.studentManage)
        self.addSubInterface(self.courseManage)
        self.addSubInterface(self.scoreManage)
        self.addSubInterface(self.teacherManage)
        self.addSubInterface(self.adminManage)

        # set Setting to bottom
        self.addSubInterface(
            self.settingInterface,
            FIF.SETTING,
            self.tr("设置"),
            NavigationItemPosition.BOTTOM,
        )

    def initWindow(self):
        self.setupUi()
        self.splashScreen = SplashScreen(self.windowIcon(), self)
        self.splashScreen.setIconSize()
        self.splashScreen.raise_()

        desktop = QApplication.desktop().availableGeometry()
        w, h = desktop.width(), desktop.height()
        self.move(w // 2 - self.width() // 2, h // 2 - self.height() // 2)
        self.show()
        QApplication.processEvents()
        print("finished")

    def resizeEvent(self, e):
        super().resizeEvent(e)
        if hasattr(self, "splashScreen"):
            self.splashScreen.resize(self.size())

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "学生管理系统"))

    def switchTo(self, interface: QWidget):
        return super().switchTo(interface)
