# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\source\python\student\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from PyQt5.QtWidgets import QApplication
from qfluentwidgets import (
    NavigationAvatarWidget,
    NavigationItemPosition,
    MessageBox,
    FluentWindow,
    SplashScreen,
)
from qfluentwidgets import FluentIcon as FIF
from common.signal_bus import signalBus


class MainWindow(FluentWindow):
    def __init__(self):
        super().__init__()
        self.initWindow()
        self.homeInterface = ()  # 登陆后开始界面
        self.personalInquiry = ()  # 个人信息查询取决于登录界面，如果是管理员登录不显示 完成
        self.studentManage = ()  # 学生管理 完成 CRUD完成
        self.courseManage = ()  # 课程管理 完成 CRUD完成
        self.scoreManage = ()  # 成绩管理 完成 CRUD
        self.teacherManage = ()  # 教师管理 开始
        self.adminManage = ()  # 管理员管理界面 未开始
        self.settingInterface = ()  # 程序设置界面 完成

        # effect enable
        self.navigationInterface.setAcrylicEnabled(isEnabled=True)
        #
        self.connectSignalToSlot()
        # init Navigation
        self.initNavigation()

    # 设置信号槽
    def connectSignalToSlot(self):
        print()

    def initNavigation(self):
        pos = NavigationItemPosition.SCROLL
        self.addSubInterface(self.homeInterface)
        self.addSubInterface(self.studentManage)
        self.addSubInterface(self.courseManage)
        self.addSubInterface(self.scoreManage)
        self.addSubInterface(self.teacherManage)
        self.addSubInterface(self.adminManage)

        # set Setting to bottom
        self.addSubInterface(
            self.settingInterface,
            FIF.SETTING,
            self.tr("设置"),
            NavigationItemPosition.BOTTOM,
        )

    def initWindow(self):
        # self.setupUi(self)
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        # self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        self.splashScreen = SplashScreen(self.windowIcon(), self)
        self.splashScreen.setIconSize(QtCore.QSize(106, 106))
        self.splashScreen.raise_()

        desktop = QApplication.desktop().availableGeometry()
        w, h = desktop.width(), desktop.height()
        self.move(w // 2 - self.width() // 2, h // 2 - self.height() // 2)
        self.show()
        QApplication.processEvents()
        print("finished")

    def resizeEvent(self, e):
        super().resizeEvent(e)
        if hasattr(self, "splashScreen"):
            self.splashScreen.resize(self.size())

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "学生管理系统"))

    def switchTo(self, interface: QWidget):
        return super().switchTo(interface)
